# Generated by Django 5.1.2 on 2024-10-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_post_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
